workers:
  - name: iii-stream
    config:
      port: 3112
      host: 127.0.0.1

  - name: iii-http
    config:
      port: 3000
      host: 127.0.0.1
      cors:
        allowed_origins:
          - '*'
        allowed_methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS

  - name: iii-state
    config:
      adapter:
        name: kv

  - name: iii-queue
    config:
      queue_configs:
        default:
          max_retries: 5
          concurrency: 10
          type: standard

  - name: iii-cron
    config:
      adapter:
        name: kv

  - name: iii-exec
    config:
      watch:
        - src/**/*.ts
      exec:
        - bun x motia dev
        - bun run dist/index-dev.js
